### ISSUE TITLE
Lazy Collection

### ISSUE THREAD

**Issue by jcampbell05** [bignerdranch/Freddy#124]
I am currently converting from data in another format (Firebase) to JSON for parsing in my models.

Its quite expensive so would love it if Freddy allowed you to provide a lazy data structure for this.

**Comment by jeremy-w** [comment]
I'm not sure I'm following the scenario. Can you provide a concrete example?

**Comment by jcampbell05** [comment]
@jeremy-w  So I have a structure from Firebase, each node has a key and a value. 

In order to use it with Freddy and my models. I have to convert it to Freddie's JSON as well as copy the key into the value of the node (As freddy doesn't seem to have a way of getting the key for the current path in the JSON.

This conversion is very expensive as I have to iterate every node in the Firebase structure.

If there was a way for example to query a path in the JSON and lazily evaluate the result that would be great. Currently Freddy assumes the JSON data structure has been prepared up front.

**Comment by jgallagher** [comment]
@jcampbell05 Sorry, I promise we're not being intentionally obtuse. I'm still not completely following. You're getting data from Firebase - is that data in JSON format? Or you're getting it in some other format and then converting it to a `Freddy.JSON`?

I'm also not sure what you mean by "getting the key for the current path in the JSON". Could you expand on that?

**Comment by jeremy-w** [comment]
An executable example in a Playground or gist would likely go a long way. You'd probably need an example data file of sufficient size to register as more than background noise when profiling the code.

I think I understand what you're asking for, but the costs in seeking through the data, creating and holding onto and forcing thunks, and branching on whether the thunk's been forced or not could wipe out any savings in not parsing the whole object. We'd also risk mis-parsing invalid JSON as valid because of mismatched `{` or `[` brackets, and the inexact parser would still have to be aware of string literals in order not to match `{` with a `}` embedded in a string when deciding what block of text to hand to the dictionary thunk.

Of course, if it just cursored into the data stream to where you requested, and re-did the parsing on each query, most of that goes away, but you pay the price of parsing the data you walk each time you do an access. It'd be a very different performance profile than the usual, but could be useful for the "huge bunch of data, but I only need one key-value pair from it" scenario.
