### ISSUE TITLE
Parse - [NSObject: AnyObject]

### ISSUE THREAD

**Issue by YMonnier** [bignerdranch/Freddy#185]
Hello,

I am facing a problem about the Freddy Json Parser. I would like to parse a JSON response from the `didReceiveRemoteNotification` function.

I cannot parse directly the userInfo response.

```
func application(application: UIApplication, didReceiveRemoteNotification userInfo: [NSObject : AnyObject]) {
   let json = JSON(userInfo)
  }
```

Have yo any ideas?
Thank you. :-)

**Comment by jgallagher** [comment]
Freddy actually includes the code needed to do this conversion, but to date we've intentionally kept it `private` because it is very slow for large payloads, and we wanted to encourage folks to use Freddy's parser rather than going through `NSJSONSerialization` and then the slow conversion. Your use case isn't one we had considered when making that decision, though. For now, a workaround could be that you could copy our implementation of this conversion (from https://github.com/bignerdranch/Freddy/blob/master/Sources/JSONParsing.swift#L52-L124) into your project. We'll discuss making this converter public again soon.

**Comment by radex** [comment]
Same issue — and same use case. Except now it's `[AnyHashable: Any]`...

**Comment by YMonnier** [comment]
@radex Thank you for the pull request!
