### ISSUE TITLE
Freddy with Swift 3 Cocoapods

### ISSUE THREAD

**Issue by frederic-adda** [bignerdranch/Freddy#195]
Hi
Is there a way to update my Cocoapods in order to have Freddy for Swift 3 ?
Currently, when I upgrade my app to Swift 3, Freddy cannot compile.

Thanks
Fred

**Comment by davidahouse** [comment]
@frederic-adda Working on a solution for this in the `swift3` branch, along with PR #208. Note that the `swift3` branch is still a work in progress and will have some API breaking changes in it due to Swift 3 API guidelines. Once that branch is able to be pulled in using cocoapods I'll let you know.

**Comment by frederic-adda** [comment]
Thanks a lot

**Comment by mdmathias** [comment]
@frederic-adda Freddy should be updates on CocoaPods now.

https://cocoapods.org/?q=Freddy

Thanks for your patience!
